version: '3.6'

x-aliases:
  - &base
      ulimits:
        core: 99999999999
      environment:
              - COMPOSER_MEMORY_LIMIT=-1
      cap_add:
        - SYS_PTRACE
  - &build_base
      context: ./
      dockerfile: Dockerfile_buster
      target: final

services:
  '7.4-debug-asan':
    <<: *base
    image: 'datadog/dd-trace-php:7.4-buster-debug-asan'
    build:
      <<: *build_base
      args: { VERSION: v7_4, VARIANT: debug-asan }
  '7.3':
    <<: *base
    image: 'datadog/dd-trace-php:7.3-buster'
    build:
      <<: *build_base
      args: { VERSION: v7_3 }
  '7.3-debug':
    <<: *base
    image: 'datadog/dd-trace-php:7.3-buster-debug'
    build:
      <<: *build_base
      args: { VERSION: v7_3, VARIANT: debug }
  '7.3-asan':
    <<: *base
    image: 'datadog/dd-trace-php:7.3-buster'
    build:
      <<: *build_base
      args: { VERSION: v7_3, VARIANT: asan }
  '7.3-debug-asan':
    <<: *base
    image: 'datadog/dd-trace-php:7.3-buster-debug-asan'
    build:
      <<: *build_base
      args: { VERSION: v7_3, VARIANT: debug-asan }
  '7.2':
    <<: *base
    image: 'datadog/dd-trace-php:7.2-buster'
    build:
      <<: *build_base
      args: { VERSION: v7_2 }
  '7.2-debug':
    <<: *base
    image: 'datadog/dd-trace-php:7.2-buster-debug'
    build:
      <<: *build_base
      args: { VERSION: v7_2, VARIANT: debug }
  '7.1':
    <<: *base
    image: 'datadog/dd-trace-php:7.1-buster'
    build:
      <<: *build_base
      args: { VERSION: v7_1}
  '7.1-debug':
    <<: *base
    image: 'datadog/dd-trace-php:7.1-buster-debug'
    build:
      <<: *build_base
      args: { VERSION: v7_1, VARIANT: debug }
  '7.0':
    <<: *base
    image: 'datadog/dd-trace-php:7.0-buster'
    build:
      <<: *build_base
      args: { VERSION: v7_0 }
  '7.0-debug':
    <<: *base
    image: 'datadog/dd-trace-php:7.0-buster-debug'
    build:
      <<: *build_base
      args: { VERSION: v7_0, VARIANT: debug }
  '5.6':
    <<: *base
    image: 'datadog/dd-trace-php:5.6-buster'
    build:
      <<: *build_base
      args: { VERSION: v5_6 }
  '5.6-debug':
    <<: *base
    image: 'datadog/dd-trace-php:5.6-buster-debug'
    build:
      <<: *build_base
      args: { VERSION: v5_6, VARIANT: debug }
  # '5.6-asan':
  #   <<: *base
  #   image: 'datadog/dd-trace-php:5.6-buster'
  #   build:
  #     <<: *build_base
  #     args: { VERSION: v5_6, VARIANT: asan }
  # '5.6-debug-asan':
  #   <<: *base
  #   image: 'datadog/dd-trace-php:5.6-buster-debug-asan'
  #   build:
  #     <<: *build_base
  #     args: { VERSION: v5_6, VARIANT: debug-asan }
  '5.4':
    <<: *base
    image: 'datadog/dd-trace-php:5.4-buster'
    build:
      <<: *build_base
      args: { VERSION: v5_4 }
  # '5.4-asan':
  #   <<: *base
  #   image: 'datadog/dd-trace-php:5.4-buster-asan'
  #   build:
  #     <<: *build_base
  #     args: { VERSION: v5_4, VARIANT: asan }
  '5.4-debug':
    <<: *base
    image: 'datadog/dd-trace-php:5.4-buster-debug'
    build:
      <<: *build_base
      args: { VERSION: v5_4 }
  # '5.4-debug-asan':
  #   <<: *base
  #   image: 'datadog/dd-trace-php:5.4-buster-debug-asan'
  #   build:
  #     <<: *build_base
  #     args: { VERSION: v5_4, VARIANT: asan }
